id: I056D4010
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:11:12.446265
last_modified: 2023-02-10 00:11:12.446409
source_metadata:
  title: 'MSV 5,00: Uttaragrantha 1'
  language: bo
bases:
  9A8E:
    base_file: 9A8E.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
